In [1]:
import numpy as np

In [3]:
a=np.array([1,7])
b=np.array([3,9])
c=np.array([2,5])
abc=np.column_stack((a,b,c))
abc

array([[1, 3, 2],
       [7, 9, 5]])

In [4]:
a=np.array([1,7])
b=np.array([3,9])
c=np.array([2,5])
abc=np.row_stack((a,b,c))
abc

array([[1, 7],
       [3, 9],
       [2, 5]])

In [5]:
a=np.array([1,7])
b=np.array([3,9])
c=np.array([2,5])
abc=np.concatenate((a,b,c))
abc

array([1, 7, 3, 9, 2, 5])

In [10]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array_split(a,5)
b

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]

In [15]:
a=np.array([i ,np.random.randint(15 ) for i in range(5) ])
a

SyntaxError: did you forget parentheses around the comprehension target? (2450259632.py, line 1)