In [1]:
import numpy as np

In [2]:
mat=np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
mat.shape

(4, 3)

In [4]:
v1=np.array([1,2,3,4,5,6,7,8,9])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
v1.shape

(9,)

In [6]:
ar=np.arange(1,100,3)
ar

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [7]:
ar1=np.arange(1,60)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [8]:
ls=np.linspace(1,10,50)
ls

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [9]:
dif=ls[1]-ls[0]
dif

0.18367346938775508

In [10]:
ls[1]

1.183673469387755

In [11]:
test_mat=np.array([[11,58,-23],
                  [85,9,2],
                  [-86,8,-5]])
test_mat

array([[ 11,  58, -23],
       [ 85,   9,   2],
       [-86,   8,  -5]])

In [13]:
np.max(test_mat)

85

In [14]:
np.min(test_mat)

-86

In [15]:
np.sum(test_mat)

59