In [1]:
import numpy as np

In [2]:
np.random.randint(1,11,10)

array([ 1,  7,  4, 10,  3,  1,  3,  6,  2,  7])

In [3]:
np.random.choice(10,10)

array([3, 4, 7, 5, 3, 9, 9, 2, 4, 6])

In [4]:
np.random.choice(10,10,replace=False)

array([6, 4, 2, 0, 9, 1, 3, 7, 8, 5])

In [24]:
np.random.choice(7)

6

In [25]:
np.random.choice(7)+1

3

In [41]:
np.random.choice(7,2)

array([4, 5])

In [42]:
np.random.choice(20,20,replace=False)

array([ 7,  8, 18, 13, 15, 16,  9, 11,  5,  3, 14,  6,  1, 17, 19,  0,  2,
       12,  4, 10])