In [1]:
import numpy as np

In [2]:
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
arr=np.arange(1,16).reshape(3,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
a=np.array([[1,5,7],
           [4,-3,7]])
a

array([[ 1,  5,  7],
       [ 4, -3,  7]])

In [11]:
a.ravel()
a

array([[ 1,  5,  7],
       [ 4, -3,  7]])

In [12]:
arr=np.random.randint(1,5,7)
arr

array([3, 2, 4, 2, 1, 2, 4])

In [14]:
pos=np.where(arr==4)
pos

(array([2, 6], dtype=int64),)

In [19]:
arr=np.random.randint(1,5,7)
print(arr)
pos=np.where(arr==4)
print(pos)

[2 3 4 1 1 3 2]
(array([2], dtype=int64),)


# TASS

In [20]:
arr=np.random.randint(1,7,10)
pos=np.where(arr>3)
print(arr)
print(pos)
print(len(pos[0]))

[3 4 5 6 4 4 2 4 4 5]
(array([1, 2, 3, 4, 5, 7, 8, 9], dtype=int64),)
8


In [22]:
arr=np.random.randint(1,7,10)
pos=np.where(arr%2==0)
print(arr)
print(pos)
print(np.size(pos))

[3 1 6 2 3 2 2 3 1 3]
(array([2, 3, 5, 6], dtype=int64),)
4
